config/routes.rb
Rails.application.routes.draw do
  root "items#index"
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  resources :users do
    resources :items
  end


  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
      post 'buy', to: 'card#buy'
      post 'index', to: 'card#index'
    end
  end
  
  resources :items do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do 
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do
      resources :purchase, only: [:index, :update] do
        collection do
          get 'index', to: 'purchase#index'
          post 'pay', to: 'purchase#pay'
          get 'done', to: 'purchase#done'
        end
      end
    end
  end

  resources :users

end

 

app/models/item.rb
class Item < ApplicationRecord
  
  belongs_to :saler, class_name: "User"
  belongs_to :buyer, class_name: "User", optional: true
  belongs_to :category, optional: true

    validates :name, :price, :status, :fee, :prefecture_id, :shipping_date, :detail, presence: { message: 'が入力されていません' }
    validates :price,  numericality: { only_integer: true ,message: '整数の数字を入力してください'}
    extend ActiveHash::Associations::ActiveRecordExtensions
    belongs_to_active_hash :prefecture
    has_many :images, dependent: :destroy
    accepts_nested_attributes_for :images, allow_destroy: true
    validates :images, presence: { message: '画像を選択してください' }
    validates :category, presence: { message: 'カテゴリーを選択してください' }
    # validates_associated :category

    # validates :price, format{
       # with: /\A\z/, message: "300円以上にしてください"
    # }
    validates :price, length: {maximum: 8, message:'9.999.999円以下にしてください'}

    enum status:{
      新品、未使用: 0,
      未使用に近い: 1,
      目立った傷や汚れなし: 2,
      やや傷や汚れあり: 3,
      傷や汚れあり: 4,
      全体的に状態が悪い: 5
    }
    enum fee:{
      送料込み（出品者負担）: 0,
      着払い（購入者負担）: 1
    }
    enum shipping_date:{
      "1~2日で発送": 0,
      "2~3日で発送": 1,
      "4~7日で発送": 2
    }
    enum stock:{
      出品中: 0,
      売却済: 1
    }
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :render_to_items_show, only: :edit

  def index
    @images = Image.all
    @items = Item.all.order("id DESC").page(params[:page]).per(3)
  end

  def show
  end

  def new
    @item = Item.new
    @item.images.new
      #セレクトボックスの初期値設定
      @category_parent_array = Category.where(ancestry: nil).pluck(:name)
      @category_parent_array.unshift("---")
  end

  def get_category_children
    #選択された親カテゴリーに紐付く子カテゴリーの配列を取得
    @category_children = Category.find_by(name: "#{params[:parent_name]}", ancestry: nil).children
  end

  def get_category_grandchildren
  #選択された子カテゴリーに紐付く孫カテゴリーの配列を取得
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end

  def create
    @item = Item.new(item_params)
    @category_parent_array = Category.where(ancestry: nil).pluck(:name)

    if @item.save
      redirect_to root_path
    else
      @category_parent_array = Category.where(ancestry: nil).pluck(:name)
      @item.images.new
      render :new
    end
  end

  def edit
    grandchild_category = @item.category
    child_category = grandchild_category.parent

    @category_parent_array = []
    Category.where(ancestry: nil).each do |parent|
      @category_parent_array << parent.name
    end

    @category_children_array = []
    Category.where(ancestry: child_category.ancestry).each do |children|
      @category_children_array << children
    end

    @category_grandchildren_array = []
    Category.where(ancestry: grandchild_category.ancestry).each do |grandchildren|
      @category_grandchildren_array << grandchildren
    end
  end

  def update
    grandchild_category = @item.category
    child_category = grandchild_category.parent
    @category_parent_array = []
    @category_parent_array = Category.where(ancestry: nil).pluck(:name)
    @category_children_array = []
    @category_children_array = Category.where(ancestry: child_category.ancestry)
    @category_grandchildren_array = []
    @category_grandchildren_array  = Category.where(ancestry: grandchild_category.ancestry)
    if @item.update(item_params)
      redirect_to item_path(@item)
    else 
      render :edit
    end
  end

  def destroy
    if user_signed_in? && current_user.id == @item.saler_id && @item.destroy
      redirect_to root_path
    else
      render :edit
    end
  end
  
  private

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :price, :size, :brand, :detail, :prefecture_id, :category_id,
                                 :status, :fee, :shipping_date, images_attributes: [:picture, :_destroy, :id]).merge(saler_id: current_user.id)
  end

  def render_to_items_show
    if current_user.id != @item.saler.id
      render file: "app/views/items/show"
    end
  end
    
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.haml
= render "shared/header"
- breadcrumb :edit_item
= render "layouts/breadcrumbs"

.main2
  .logo
  = image_tag 'material/logo/logo.png', size: "180x70",class:'logo2'

  .itemBox
    .itemBox__title 商品の情報を入力
    .imageForm
    = form_for @item, url: {action: "update"} do |f|
      -if @item.errors.any? 
        .alert
          %ul
            - @item.errors.full_messages.each do |message| 
              %li= message
      .imageForm__top
        =f.label :出品画像 
        %span.red 必須
      .imageForm__text
        %p 最大10枚までアップロードできます。
      .imageForm__form
        #image-box
          #previews
            - if @item.persisted?
              - @item.images.each_with_index do |image, i|
                = image_tag image.picture.url, data: { index: i }, width:"100", height:'100' 
          = f.fields_for :images do |i|
            .js-file_group{"data-index" => "#{i.index}"}
              = i.file_field :picture, class: "js-file"
              %br
              .js-remove 削除
              
            - if @item.persisted?
              = i.check_box :_destroy, data: { index: i.index }, class:"hidden-destroy"
          - if @item.persisted?
            .js-file_group{"data-index"  => "#{@item.images.count}"} 
              = file_field_tag :picture, name: "item[images_attributes][#{@item.images.count}][picture]", class: 'js-file' 
              .js-remove 削除
      .name
        .name__top
          =f.label :商品名
          %span.red 必須
        .name__form
          = f.text_field :name, placeholder: "商品名を入力", class: "text-test"

      .explain
        .explain__top
          =f.label :商品の説明
          %span.red 必須
        .explain__form
          = f.text_area :detail, placeholder: "商品の説明を入力", class: "textarea-test"

      .detail
        .listing-form-box
          .listing-product-detail__category
            = f.label 'カテゴリー', class: 'listing-default__label'
            %span.listing-default--require 必須
            

            .listing-select-wrapper
              .listing-select-wrapper__box
                = f.select :parent_name, @category_parent_array, {selected:@item.category.parent.parent.name}, {class: 'listing-select-wrapper__box--select', id: 'parent_category', name: "category"}
                %i.fas.fa-chevron-down.listing-select-wrapper__box--arrow-down-1
              .listing-select-wrapper__box
                = f.select :category_id, options_for_select(@category_children_array.map{|b| [b.name, b.id, {data:{category: b.id}}]}, {prompt: "指定なし", selected: @item.category.parent.id}),{}, {class: 'listing-select-wrapper__box--select', id: 'children_wrapper', name: "category"}
                %i.fas.fa-chevron-down.listing-select-wrapper__box--arrow-down
              .listing-select-wrapper__box
                = f.select :category_id, options_for_select(@category_grandchildren_array.map{|b| [b.name, b.id, {data:{category: b.id}}]}, {prompt: "指定なし", selected: @item.category.id}),{},  {class: 'listing-select-wrapper__box--select', id: 'grandchildren_wrapper', name: "category"}
                %i.fas.fa-chevron-down.listing-select-wrapper__box--arrow-down

        .bland
          .bland__name
            =f.label :ブランド
            %span.gray 任意
          .bland__form
          = f.text_field :brand, placeholder: "ブランドを入力", class: "text-test"

        .size
          .size__name
            =f.label :商品のサイズ
            %span.gray 任意
          .size__form
          = f.text_field :size, placeholder: "サイズを入力", class: "text-test"

        .status
          .status__name
            =f.label :商品の状態
            %span.red 必須
          .status__form
            = f.select :status, Item.statuses.keys.to_a,  {prompt: "選択してください"}, {class: 'select-test'}
            

      .shipping
        .fee
          %p.grayP 送料について
          .fee__name
            =f.label :配送料の負担
            %span.red 必須
          .fee__form
            = f.select :fee, Item.fees.keys.to_a,  {prompt: "選択してください"}, {class: 'select-test'}

        .region
          .region__name
            =f.label :発送元の地域
            %span.red 必須
          .region__form
          = f.collection_select :prefecture_id, Prefecture.all, :id, :name, {prompt: "選択してください"}, {class: 'select-test'}
              
        .date
          .date__name
            =f.label :発送までの日数
            %span.red 必須
          .date__form
            = f.select :shipping_date, Item.shipping_dates.keys.to_a,  {prompt: "選択してください"}, {class: 'select-test'}
      .prices
        .price
          %p.grayLittle 価格（¥300〜9,999,999）
          .price__box
            .price__box__total
              =f.label :販売価格
              %span.red 必須
            .price__box__form
              = f.text_field :price, placeholder: "販売価格を入力", class: "text-test"
          
      .sure
        = f.submit "出品する", class: 'submit-test redButtom'
        = link_to "戻る", root_path, class: 'submit-test grayButtom'
    .warning
      %p 禁止されている行為および出品物を必ずご確認ください。偽ブランド品や盗品物などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして加盟店規約に同意したことになります。
= render "shared/footer"

app/views/items/index.html.haml
= render "shared/header"

.main
  .topPage
    .topPage__box
      .topPage__box__content
        %h1 人生を変えるフリマアプリ
      .topPage__box__text
        %p
          FURIMAはだれでもかんたんに出品・購入できる
          %br
            フリマアプリです
      .topPage__box__images
        .topPage__box__images__abtn
          = link_to"#" do
            = image_tag "material/app-store-image.svg", size:"180x53",alt:"test"
        .topPage__box__images__gbtn
          = link_to"#" do
            = image_tag "material/google-play-image.svg", size:"180x53",alt:"test"

  .orderPage
    .orderPage__title
      %h1 FURIMAが選ばれる３つの理由
    %ul.orderPage__images
      %li.orderPage__images__image
        .orderPage__images__image__pict
          =image_tag"material/pict/pict-reason-01.jpg",size:"306x306",alt:"test"
          %span.number 1
        %h3.list__text
          %span 3分
          ですぐに出品
        %p.list__description  スマホで入力するだけで簡単に出品できる！
      
      %li.orderPage__image
        .orderPage__images__image
          .orderPage__images__image__pict
            = image_tag "material/pict/pict-reason-02.jpg", size:"306x306",alt:"test"
            %span.number 2
          %h3.list__text
            %span シンプル
            で使いやすい
          %p.list__description  めんどくさい入力は必要なく、検索も購入もスムーズ！
      
      %li.orderPage__image
        .orderPage__images__image
          .orderPage__images__image__pict
            = image_tag "material/pict/pict-reason-03.jpg", size:"306x306",alt:"test"
            %span.number 3
          %h3.list__text
            手数料
            %span 業界最安
          %p.list__description  最大3%でお得に出品&購入！

  
  .topDLpage
    .topDLpage__box
      .topDLpage__box__title
      %h2 会員数日本一位
      .topDLpage__box__text
      %p 
        FURIMAは、フリマアプリで最も人気
        %br 
          出品・購入回数も業界最多です！
          %br
            ほしかったあの商品に出会えるかもしれません。
      .topDLpage__box__btns
        .topDLpage__box__btns__abtn
          = link_to"#" do
            = image_tag "material/app-store-image.svg", size:"180x53",alt:"test"
        .topDLpage__box__btns__gbtn
          = link_to"#" do
            = image_tag "material/google-play-image.svg", size:"180x53",alt:"test"





  .featurePage
    .featurePage__title
      %h1 FURIMAの特徴
    .featurePage__images
      .featurePage__images__image
        .featurePage__images__image__pict
        = image_tag "material/icon/icon-01.png",size:"229x338",alt:"test"
        %h3.image__subTitle 簡単に売り買いできる
        %p.image__sentence スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
      .featurePage__images__image
        .featurePage__images__image__pict
        = image_tag "material/icon/icon-03.png",size:"229x338",alt:"test"
        %h3.image__subTitle 売上金は即日振込みに対応
        %p.image__sentence  午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
      .featurePage__images__image
        .featurePage__images__image__pict
        = image_tag "material/icon/icon-04.png",size:"229x338",alt:"test"
        %h3.image__subTitle 様々な支払いに対応
        %p.image__sentence  お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。







  .pickupItem
    %h2.text ピックアップアイテム
    .pickupItem__box
      .pickupItem__box__head
        = link_to "" do
          %h3.head__title 新規商品一覧
      .pickupItem__box__lists
        - @items.each do |item|
          = link_to item_path(item.id), method: :get do
            %figure.pickupItem__box__lists__list
              .pickupItem__box__lists__list__image
                = image_tag item.images[0].picture_url
              .pickupItem__box__lists__list__body
                %h3.pickupItem__box__lists__list__body__name
                  = item.name
                .pickupItem__box__lists__list__body__details
                  %ul
                    %li
                      = item.price
                      = "円"
                    %li
                      %i.fa.fa-star.likeicon #{item.favorites.count}
                  %p (税込)
                  - if item.buyer_id.present?
                    %p2.pickupItem__box__lists__list__body__details__soldout Sold Out




  .pickupItem
    %h2.text ピックアップアイテム
    .pickupItem__box
      .pickupItem__box__head
        = link_to "#" do
          %h3.head__title 商品一覧
      .pickupItem__box__lists
        = link_to "#" do
          %figure.pickupItem__box__lists__list
            .pickupItem__box__lists__list__image
              = image_tag "material/item01.png"
            .pickupItem__box__lists__list__body
              .pickupItem__box__lists__list__body__name
              %h3 product3
              .pickupItem__box__lists__list__body__details
                %ul
                  %li 30000円
                  %li
                    %i.fa.fa-star.likeicon 0
                %p (税込)
        = link_to "#" do
          %figure.pickupItem__box__lists__list
            .pickupItem__box__lists__list__image
              = image_tag "material/item02.png"
            .pickupItem__box__lists__list__body
              .pickupItem__box__lists__list__body__name
              %h3 product2
              .pickupItem__box__lists__list__body__details
                %ul
                  %li 20000円
                  %li
                    %i.fa.fa-star.likeicon 0
                %p (税込)

        
        = link_to "#" do
          %figure.pickupItem__box__lists__list
            .pickupItem__box__lists__list__image
              = image_tag "material/item03.png"
            .pickupItem__box__lists__list__body
              .pickupItem__box__lists__list__body__name
              %h3 product1
              .pickupItem__box__lists__list__body__details
                %ul
                  %li 10000円
                  %li
                    %i.fa.fa-star.likeicon 0
                %p (税込)



= link_to new_item_path do
  %fugure.exhibitionBtn
    %span.text 出品する
    .exhibitionBtn_icon
    =image_tag "material/icon/icon_camera.png",size:"54x54"


= render "shared/footer"

app/views/items/new.html.haml
= render "shared/header"
- breadcrumb :new_item_path
= render "layouts/breadcrumbs"

.main2
  .logo
  = image_tag 'material/logo/logo.png', size: "180x70",class:'logo2'
  
  .itemBox
    = form_for @item, url: {action: "create"} do |f|
      -if @item.errors.any? 
        .alert
          %ul
            - @item.errors.full_messages.each do |message| 
              %li= message 
      .imageForm
        .imageForm__top
          =f.label :出品画像 
          %span.red 必須
        .imageForm__text
          %p 最大10枚までアップロードできます。
        .imageForm__form
          #image-box
            = f.fields_for :images do |i|
              .js-file_group{"data-index" => "#{i.index}"}
                = i.file_field :picture, class: "js-file"
                %br
                .js-remove 削除

      .name
        .name__top
          =f.label :商品名
          %span.red 必須
        .name__form
          = f.text_field :name, placeholder: "商品名を入力", class: "text-test"

      .explain
        .explain__top
          =f.label :商品の説明
          %span.red 必須
        .explain__form
          = f.text_area :detail, placeholder: "商品の説明を入力", class: "textarea-test"

      .detail
        .category
          .listing-product-detail__category
            = f.label 'カテゴリー', class: 'listing-default__label'
            %span.listing-default--require 必須
            .listing-select-wrapper
              .listing-select-wrapper__box
                .category__form
                  = f.select :category_id, @category_parent_array, {}, {class: 'select-test', id: 'parent_category', name: "category"}
                  %i.fas.fa-chevron-down.listing-select-wrapper__box--arrow-down
        .bland
          .bland__name
            =f.label :ブランド
            %span.gray 任意
          .bland__form
            = f.text_field :brand, placeholder: "ブランドを入力", class: "text-test"

        .size
          .size__name
            =f.label :商品のサイズ
            %span.gray 任意
          .size__form
            = f.text_field :size, placeholder: "サイズを入力", class: "text-test"

        .status
          .status__name
            =f.label :商品の状態
            %span.red 必須
          .status__form
            = f.select :status, Item.statuses.keys.to_a,  {prompt: "選択してください"}, {class: 'select-test'}
            

      .shipping
        .fee
          %p.grayP 送料について
          .fee__name
            =f.label :配送料の負担
            %span.red 必須
          .fee__form
            = f.select :fee, Item.fees.keys.to_a,  {prompt: "選択してください"}, {class: 'select-test'}

        .region
          .region__name
            =f.label :発送元の地域
            %span.red 必須
          .region__form
            = f.collection_select :prefecture_id, Prefecture.all, :id, :name, {prompt: "選択してください"}, {class: 'select-test'}
              
        .date
          .date__name
            =f.label :発送までの日数
            %span.red 必須
          .date__form
            = f.select :shipping_date, Item.shipping_dates.keys.to_a,  {prompt: "選択してください"}, {class: 'select-test'}
      .prices
        .price
          %p.grayLittle 価格（¥300〜9,999,999）
          .price__box
            .price__box__total
              =f.label :販売価格
              %span.red 必須
            .price__box__form
              = f.text_field :price, placeholder: "販売価格を入力", class: "text-test"
        
      .sure
        = f.submit "出品する", class: 'submit-test redButtom'
        = link_to "戻る", root_path, class: 'submit-test grayButtom'

    .warning
      %p 禁止されている行為および出品物を必ずご確認ください。偽ブランド品や盗品物などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして加盟店規約に同意したことになります。
= render "shared/footer"

app/views/items/show.html.haml
= render "shared/header"
- breadcrumb :item
= render "layouts/breadcrumbs"

.main 
  .showMain
    .rightContent
      .topContent
        .itemBox2
          .itemBox2__name
            = @item.name
          .itemBox2__body__main
            %ul
              %li.mainImage 
                = image_tag @item.images[0].picture.url, size:"560x346"
          .itemBox2__body__sub
            %ul.subImage
              - @item.images.each do |image|
                %li
                  = image_tag image.picture.url, size:"140x87"
          .itemBox2__price
            %span ¥#{@item.price}
            .itemBox2__price--detail
              %span （税込）送料込み

          - if user_signed_in? && current_user.id != @item.saler_id
            .itemBuyBtn 
              = link_to "購入画面に進む", purchase_index_path(@item.id), class:"buyBtn"
        
          .itemDetail
            = @item.detail

          .table
          %table{:border => "1"}
            %tr
              %th.left-top 出品者 
              %th.right-top 
                = @item.saler.nickname
            %tr
              %td.left-lists カテゴリー
              %td.right-lists 
                = link_to @item.category.root.name,"#" 
                %br
                = link_to @item.category.parent.name,"#" 
                %br
                = link_to @item.category.name,"#" 
            %tr
              %td.left-lists ブランド
              %td.right-lists 
                = @item.brand
            %tr
              %td.left-lists 商品のサイズ
              %td.right-lists 
                = @item.size
            %tr
              %td.left-lists 商品の状態
              %td.right-lists 
                = @item.status
            %tr
              %td.left-lists 配送料の負担
              %td.right-lists
                #{@item.fee}円
            %tr
              %td.left-lists 発送元の地域
              %td.right-lists
                = @item.prefecture.name
            %tr
              %td.left-lists 発送日の目安
              %td.right-lists
                = @item.shipping_date
          .optionalArea
            %ul
              %li.optionalBtnLikebtn
                = link_to "#", class: "likeBtn" do
                  = icon('fas fa-star fa-xs', class: 'starIcon')
                  %p.textFavorite お気に入り 0
            %ul.optional
              %li.optionalBtn
                = link_to "#", class: "reportBtn" do
                  = icon('fa fa-flag fa-xs', class: 'flagIcon')
                  %p.textReport 不適切な商品の通報


        - if user_signed_in? && current_user.id == @item.saler_id
          .editBox
            = link_to "商品の編集", edit_item_path(@item.id), class:"itemEditBtn"
            %p.or or
            = link_to "出品の一旦停止をする", "#", class:"itemStopBtn"
            = link_to "この商品を削除する", item_path(@item.id), method: :delete, class:"itemDestroyBtn"            

        .commentBox
          %ul.commentContents
            = form_for "#" do |f|
              = f.text_area :text, class: 'comment'
              %p.noticeMsg 
                相手のことを考え丁寧なコメントを心がけましょう。
                %br 
                  不快な言葉遣いなどは利用制限や退会処分となることがあります。
              .commentBtnBox
                = icon('fas fa-comment', class: 'commentIcon')
                = f.submit class: 'commentBtn', value: 'コメントする'
        %ul.links 
          = link_to "< 前の商品", "#", class: "itemLinks"
          = link_to "後ろの商品 >", "#", class: "itemLinks"
        .relatedItems
          = link_to "メンズをもっと見る", "#", class: "productLists"
= render "shared/footer"