config/routes.rb
Rails.application.routes.draw do
  root "items#index"
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  resources :users do
    resources :items
  end


  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
      post 'buy', to: 'card#buy'
      post 'index', to: 'card#index'
    end
  end
  
  resources :items do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do 
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do
      resources :purchase, only: [:index, :update] do
        collection do
          get 'index', to: 'purchase#index'
          post 'pay', to: 'purchase#pay'
          get 'done', to: 'purchase#done'
        end
      end
    end
  end

  resources :users

end

 

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user

  validates :user_id, :customer_id, :card_id, presence: { message: 'が入力されていません' }
end

app/controllers/card_controller.rb
class CardController < ApplicationController

  require "payjp"
  before_action :set_card

  def new
    card = Card.new
    if @card.present?
      redirect_to action: "show"
    end
  end

  def pay 
    Payjp.api_key = Rails.application.credentials.payjp[:PAYJP_ACCESS_KEY]
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
      description: '登録テスト',
      email: current_user.email, 
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      ) 
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: "show"
        flash[:success] = '登録に成功しました'
      else
        redirect_to action: "pay"
        flash[:alart] = '登録に失敗しました'
      end
    end
  end

  def delete 
    if @card.present?
      Payjp.api_key = Rails.application.credentials.payjp[:PAYJP_ACCESS_KEY]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      customer.delete
      @card.delete
    end
      redirect_to controller: "card", action: "new"
      flash[:success] = '登録を削除しました'
  end

  def show 
    if @card.blank?
      redirect_to controller: "card", action: "new"
    else
      Payjp.api_key = Rails.application.credentials.payjp[:PAYJP_ACCESS_KEY]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)
    end
  end
end

private

def set_card
  @card = Card.where(user_id: current_user.id).first if Card.where(user_id: current_user.id).present?
end

app/helpers/card_helper.rb
module CardHelper
end

app/views/card/new.html.haml
= render "shared/header"
- breadcrumb :card
= render "layouts/breadcrumbs"

.mainUser
  .left
    .leftUpper
      %table
        %tr
          %th
            =link_to "マイページ", user_path(current_user.id)
        %tr
          %td
            =link_to 'いいねした商品'
        %tr
          %td
            %ul
              %li イーチぶんでいいね
              %li した商品を
              %li 上から3つ表示
        %tr
          %td
            =link_to '出品した商品'
        %tr
          %td
            =link_to 'コメントした商品'
        %tr
          %td
            =link_to '出品'
        %tr
          %td
            =link_to 'お問い合わせ'
    .leftBottom
      %table
        %tr
          %th
            ユーザー情報
        %tr
          %td
            =link_to destroy_user_session_path,method: :delete do
              ログアウト
        %tr
          %td
            =link_to '情報変更'
        %tr
          %td
            =link_to "クレジットカード登録", new_card_path,data:{"turbolinks" => false}
        %tr
          %td
            =link_to 'クレジットカード変更'

  .cardBox
    .cardBox__name
      %h2 カード情報入力
    .cardBox__reg
      = form_tag(pay_card_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
        %label カード番号
        = text_field_tag "number", "", class: "number", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
        %br
        %label 有効期限
        %select#exp_month{name: "exp_month", type: "text"}
          %option{value: ""} --
          %option{value: "1"}01
          %option{value: "2"}02
          %option{value: "3"}03
          %option{value: "4"}04
          %option{value: "5"}05
          %option{value: "6"}06
          %option{value: "7"}07
          %option{value: "8"}08
          %option{value: "9"}09
          %option{value: "10"}10
          %option{value: "11"}11
          %option{value: "12"}12
        %span 月/
        %select#exp_year{name: "exp_year", type: "text"}
          %option{value: ""} --
          %option{value: "2019"}19
          %option{value: "2020"}20
          %option{value: "2021"}21
          %option{value: "2022"}22
          %option{value: "2023"}23
          %option{value: "2024"}24
          %option{value: "2025"}25
          %option{value: "2026"}26
          %option{value: "2027"}27
          %option{value: "2028"}28
          %option{value: "2029"}29
        %span 年
        %br
        %label セキュリティコード
        = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
        #card_token
        = submit_tag "追加する", id: "token_submit"

= render "shared/footer"

app/views/card/show.html.haml
= render "shared/header"
- breadcrumb :card_show
= render "layouts/breadcrumbs"

.mainUser
  .left
    .leftUpper
      %table
        %tr
          %th
            =link_to "マイページ", user_path(current_user.id)
        %tr
          %td
            =link_to 'いいねした商品'
        %tr
          %td
            %ul
              %li イーチぶんでいいね
              %li した商品を
              %li 上から3つ表示
        %tr
          %td
            =link_to '出品した商品'
        %tr
          %td
            =link_to 'コメントした商品'
        %tr
          %td
            =link_to '出品'
        %tr
          %td
            =link_to 'お問い合わせ'
    .leftBottom
      %table
        %tr
          %th
            ユーザー情報
        %tr
          %td
            =link_to destroy_user_session_path,method: :delete do
              ログアウト
        %tr
          %td
            =link_to '情報変更'
        %tr
          %td
            =link_to "クレジットカード登録", new_card_path
        %tr
          %td
            =link_to 'クレジットカード変更'

  .cardBox
    .cardBox__name
      %h2 支払い情報
    .cardBox__info
      %label クレジットカード一覧
      .cardBox__info__number
        = "**** **** **** " + @default_card_information.last4
        %br
        - exp_month = @default_card_information.exp_month.to_s
        - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
        = exp_month + " / " + exp_year
        = form_tag(delete_card_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
          %input{ type: "hidden", name: "card_id", value: "" }
          %button 削除する
      .cardBox__explain
        = link_to 'お支払方法について'

= render "shared/footer"